---
title: "Daily Journal"
author: "N. Harms"
format: pdf
editor: visual
---

## 6/4

-   Collab meeting

## 6/5

-   Started training- Intro-part of module 2

## 6/7

-   Finished module 2 of training

## 6/9

-   Worked on training

## 6/10

-   Finished training

## 6/11

-   Meeting with Susan & Toma at 12
-   Group meeting at 2

## 6/12

-   Worked on write-up

## 6/17

-   Finish up write-up
-   Created a markdown file of WCAG 2.1 AA guidelines (to have a concise easy-access list)

## 6/18

-   Meeting at 2
-   Quarto/Pandoc research
-   Ask Susan about HTML/Quarto/Pandoc/all the things materials

## To-do...

-   Accessibility check for 850 book
    -   Go through WCAG 2.1 Level AA standards (markdown file created)
-   Read up on Quarto: [Mine-Cetinkaya](https://mine-cr.com/about/)
-   Get in touch with Reka
-   Read through [Understanding Techniques for WCAG Success Criteria](https://www.w3.org/TR/2014/NOTE-UNDERSTANDING-WCAG20-20140916/understanding-techniques.html#understanding-techniques)

## Other thoughts...

-   Perhaps create a website with finished materials?
    -   Like slide templates
-   Easy to follow "guidelines" for department use
