---
title: "Accessibility Rules!"
subtitle: "Orientation Week 2025"
author: "Nicole Harms"
format: 
  revealjs: 
    chalkboard: true
    theme: simple
    link-external-newwindow: true
    link-external-icon: true
    html-math-method: mathjax
    logo: logo.jpg
editor: visual
---

# Introduction

## What I've Been Doing...

-   Researching and learning about accessibility

-   Finding best practices

-   Breaking it down into digestible pieces

-   Creating content for the department

# Accessibility: High Level Overview

## Title II {.center}

-   Refers to Title II of the Americans with Disabilities Act (ADA)

-   Applies to public entities such as:

    -   Schools
    -   Colleges
    -   State and local governments
    -   Healthcare providers

-   Don't have to receive funding to fall under the scope of Title II

## Title II {.center}

Serves two main purposes:

-   Prohibits the discrimination of a disabled individual by previously described public entities

-   Requires all individuals be able to benefit from and access their services

## Title II Examples {.center}

-   Accessible buildings

-   Online materials are accessible

-   Allowing service animals

-   "Accessible" = anyone can access

::: notes
Accessible is easy to think about when it comes to something like a building. Not as easy to conceptualize when it comes to documents or online materials.
:::

## Web Content Accessibility Guidelines (WCAG) {.center}

-   Department of Justice (DOJ) published a new rule in April 2024 outlining accessibility regulations

-   WCAG are developed by World Wide Web Consortium (W3C)

-   Web content must meet WCAG Version 2.1, Level AA standards

    -   Levels range from A to AAA
    -   AAA is highest accessibility

## WCAG Overview

Each guideline falls into one of four categories of the **POUR** acronym:

-   [**P**]{.underline}erceivable

-   [**O**]{.underline}perable

-   [**U**]{.underline}nderstandable

-   [**R**]{.underline}obust

The POUR acronym is commonly used to recall guidelines.

-   A full list of guidelines can be found here: [WCAG Quick Reference](https://www.w3.org/WAI/WCAG22/quickref/?versions=2.1)

## Perceivable {.center}

"Information and user interface components must be presentable to users in ways they can perceive."

-   Alternative (alt) text

-   Closed captioning

-   Color contrast/schemes

-   Text size and spacing

-   Display orientation


## Operable {.center}

"User interface components and navigation must be operable."

-   Keyboard navigation

-   Keyboard focus is visible

-   Ability to adjust timed content

-   Content is in readable order (focus order)

## Understandable {.center}

"Information and the operation of the user interface must be understandable."

-   No unusual language (slang) is used

-   Abbreviations are explained

-   Webpage navigation is consistent and predictable

-   Input fields provide assistance and error assistance

## Robust {.center}

"Content must be robust enough that it can be interpreted by a wide variety of user agents, including assistive technologies."

-   Elements of a page or document are correctly tagged and labeled

-   Nesting according to specifications

. . . 

Anything HTML or XML is considered to have met this criteria!

# Best Practices

## How does this apply to you? {.center}

Your content should be made accessible if:

::: incremental
-   You are distributing it to students

    -   Slides
    -   PDFs
    -   Lecture videos

-   It is a website for your class

-   It will be distributed on our department website for public use
:::

## Materials you do not need to check {.center}

-   Content provided by a book publisher

    -   Slides
    -   PDFs
    -   Lecture videos

-   Presumed accessible if they're distributed by a publisher

## Slide Accessibility {.center}

-   Less is more!

-   Main components to check:

    -   Alternative text
    -   Links
    -   Color contrast
    -   Overall formatting

## Slide Accessibility {.center}

-   In general, HTML based slides are best

    -   Quarto/Revealjs

-   Powerpoint

    -   Has built-in accessibility checker

-   Printing slides to a PDF is generally the least accessible

    -   Requires extra steps to make accessible

## Slide Accessibility {.center}

Annotating

-   Annotations made in class are unfortunately not accessible

-   Alt text should be added only if slides are to be distributed

    -   You can still do annotations in class!

## PDF Accessibility {.center}

-   Trickier to do

-   Adobe is essentially the only option

-   Has automatic accessibility checker

-   Can add alt text, document structure tags, etc.

-   Accessibility of a PDF largely depends on how its source document was structured

-   [PDF Accessibility](https://www.adobe.com/acrobat/hub/what-is-an-accessible-pdf.html)

## Graphic Accessibility {.center}

-   Not always possible to make graphics fully accessible

-   Alt text

    -   Useful, but often difficult to fully explain a graphic

    -   Packages like `BrailleR` generate alt text

-   `svg`-based web graphics are a good alternative

    -   Ex: `d3`, `Observable.js`, `Highcharts.js`

-   Accessibility [training](https://srvanderplas.github.io/workshop-graphics-communication/content/03-accessibility.html#fig-olli-penguin) by Dr. VanderPlas

## To summarize... {.center}

-   Make materials accessible within reason

-   "Big items" to check

    ::: incremental
    -   Alternative text
    -   Keyboard checks
    -   Color contrast
    :::

## Other areas to pay attention to {.center}

-   Links

    -   Make sure links are descriptive

-   Avoid slang or abbreviations that may be difficult to understand

-   Overall document structure

    -   Headings, layout, etc.

## Other areas to pay attention to {.center}

-   Font size/spacing

-   Emojis are OK, but:

    -   Ensure you're using emojis, not emoticons
        -   Emoji: 😁
        -   Emoticon: :)
    -   Use sparingly

# Resources

## Canvas

-   Canvas should now automatically check material accessibility

    -   Works for uploaded files

    -   Not insanely reliant, but gives a good estimate

-   YuJa

    -   For lecture recordings, automtatically provides closed captioning

## Automatic Website Checkers {.center}

-   IBM Accessibility Checker extension

    -   False positive rate is high
    -   But, gives a good idea of areas that could be improved

-   WAVE Web Accessibility Evaluation Tool

    -   Checks websites for accessibility

## Other Useful Resources

-   Repo link
-   IBM accessibility checker
-   Color contrast checker
-   

## References

https://www.ada.gov/resources/2024-03-08-web-rule/
